### ISSUE TITLE
find_or_create_by_?

### ISSUE THREAD

**Issue by frugardc** [chicks/sugarcrm#17]
I am getting "false" when attempting this.  Is this functionality in there, or does it just think I am doing a query that is returning no results?

**Comment by chicks** [comment]
Can you give me some code to reproduce?

**Comment by davidsulc** [comment]
This functionality is present in the code. Could you provide the code you're running (i.e. the `find_or_create_by` call) so we can see where it's tripping up? It's possible the issue is taking place during the creation: the instance can't be created and is returning `false`

**Comment by frugardc** [comment]
This should illustrate it pretty well.  An Account only has one required field, :name, and I try a find_or_create_by_name and get false...

irb(main):052:0> SugarCRM::Account.new.required_attributes
=> [:name]
irb(main):053:0> SugarCRM::Account.find_or_create_by_name("Something Silly")
=> false

**Comment by frugardc** [comment]
irb(main):052:0> SugarCRM::Account.new.required_attributes

=> [:name]

irb(main):053:0> SugarCRM::Account.find_or_create_by_name("Something Silly")

=> false

**Comment by chicks** [comment]
Oh, I don't think I ever tested this.  We'll probably have to make some changes for this to work.  find_by_name works though, right?

Thanks for the bug!

**Comment by davidsulc** [comment]
I can't quite figure this out. It seems that:
1. Base#initialize should be modified to yield if block is given (which is the case in find_or_create_by)
2. @modified_attributes doesn't get populated correctly preventing the `save` from taking place (because `changed?` is false)

But I didn't find out where `@modified_attributes` is updated...

It seems `find_or_initialize_by` works correctly after adding `yield(self) if block_given?` to `Base#initialize`.

Chicks, can you look into the `@modified_attributes` issue when you get the chance?

**Comment by chicks** [comment]
I'll take a look.

**Comment by davidsulc** [comment]
See HEAD in my repo for the fix for `find_or_initialize_by`

**Comment by chicks** [comment]
This is fixed.  I'll cut a new gem before I go to bed tonight.
