### ISSUE TITLE
in rails app SugarCRM::MultipleSessions (There are multiple active sessions: use the session namespace instead of SugarCRM):

### ISSUE THREAD

**Issue by ketanjm** [chicks/sugarcrm#36]
hey  i am getting error when sugarcrm gem usng i rails application 
like this

SugarCRM::MultipleSessions (There are multiple active sessions: use the session namespace instead of SugarCRM):

gem "sugarcrm", "0.9.11"
rails version = 3.0.3

how to use namespace session for SugarCRM?

**Comment by davidsulc** [comment]
Each time you call `SugarCRM.connect`, the gem will create a new session (this is so you can connect several servers simultaneously). What you may want to look into is why your rails app is connecting several times. Do you have the connection code in an initializer?

To answer your question: the gem returns the namespace when calling `SugarCRM.connect`, so do something like this

```
MyCRMServer = SugarCRM.connect(...)
```

Do NOT put `SugarCRM` as the variable name, or you will have major issues.

Then, in your code, you use the gem by calling methods on `MyCRMServer` instead of `SugarCRM`:

```
MyCRMServer::Account.first
```

**Comment by ketanjm** [comment]
thanks 
 yeah i had  "SugarCRM.connect"    in  initialize method

**Comment by davidsulc** [comment]
Hmm. This is something we'll have to address in an upcoming version.

**Comment by ketanjm** [comment]
even if i moved  SugarCRM.connect(@url, @username, @password) to spacific methods  !!! and calling multiple time  it gonna give me same error multiple session !
its need to be close session !!! i tried using "disconnect"  method of  connection.rb but not worked !!!!!! 
and 
its take  much time to import  data !!!
Thanks !!!!

**Comment by davidsulc** [comment]
Can you clarify a few things:
- what do you mean by moving SugarCRM.connect(@url, @username, @password) to specific methods?
- why are you calling SugarCRM.connect multiple times?
- how did you call the `disconnect` method?

If you're importing large sets of data, you might want to try Sugar's import feature, and feeding it a CSV file with your data.

**Comment by davidsulc** [comment]
Until we can look into this issue properly, I suggest you put the following code in your initializer:

```
if SugarCRM.namespaces.size > 0
  SugarCRM.connect(...)
else
  SugarCRM.reconnect(...)
end
```

Replace the ... with your credentials (username, etc.) and it should solve all your issues. You can then call your methods on the SugarCRM object (e.g. `SugarCRM::User.first`).

**Comment by ketanjm** [comment]
HI,
I was trying  
if SugarCRM.current_user
  SugarCRM.disconnect(...)
end
  SugarCRM.connect(...)

but gave 

SugarCRM::NoActiveSession (No session is active. Create a new session with 'SugarCRM.connect(...)')

And
the solution u gave,  is not working same like that !!!!
giving me result  

SugarCRM::MultipleSessions (There are multiple active sessions: use the session namespace instead of SugarCRM):

but     the module i created will work when i run it from out side of the rails app !!!!

**Comment by davidsulc** [comment]
Terribly sorry, I somehow managed to switch the cases. The code you should have in the initializer (modified slightly for robustness):

```
case SugarCRM.namespaces.size
when 0
  SugarCRM.connect(...)
when 1
  SugarCRM.reconnect(...)
else
  raise "Multiple sessions in Rails initializer (shouldn't happen!)"
end
```

This should work.

The reason your code above failed is that to find out who the current user connected to SugarCRM is, we need an active connection (because we need to ask SugarCRM through the REST API). In the case where no active session exists, the error you saw will be raised.

One way to modify your code to work as intended would be

```
begin
  SugarCRM.disconnect if SugarCRM.current_user
rescue SugarCRM::NoActiveSession => e
  # do nothing: no active session
end
SugarCRM.connect(...)
```

Be advised that this version will fail if (for whatever reason) there are multiple active connections, which shouldn't happen.

**Comment by ketanjm** [comment]
failing again !

# For code !!!

begin
  SugarCRM.disconnect if SugarCRM.current_user
rescue SugarCRM::NoActiveSession => e
  # do nothing: no active session
end

# SugarCRM.connect(...)

# NameError (uninitialized constant SugarCRM::Namespace0::User):

# and for 

case SugarCRM.namespaces.size
when 0
  SugarCRM.connect(...)
when 1
  SugarCRM.reconnect(...)
else
  raise "Multiple sessions in Rails initializer (shouldn't happen!)"

# end

# NameError (constant SugarCRM::Namespace0::Task not defined):

**Comment by davidsulc** [comment]
Can you open an irb session (by e.g. typing `irb` at the command prompt) and enter the following

```
require 'sugarcrm'
SugarCRM.connect(...)
SugarCRM::User.first
```

and tell me what the output is?

**Comment by ketanjm** [comment]
it works fine outside rails app 
any number of times!! 
problem is failing with rails app !!!
even i skip session and caching  in app !

**Comment by ketanjm** [comment]
done!!!! : ) 
i change my code

in initialzers

@a =  SugarCRM.connect(@url, @username, @password)

```
  if @a ==  SugarCRM::Namespace1
    @a.disconnect  #if SugarCRM.current_user
    SugarCRM.connect(@url, @username, @password) 
  #else 
   # SugarCRM.connect(@url, @username, @password)
```

   end  

and 

using like that !!!
    def get_contacts  
      emails = []
      begin
        contacts = SugarCRM::Namespace0::Contact.find(:all)  # , :include => [:accounts])  
      rescue 
        contacts = @a.Contact.find(:all)  # , :include => [:accounts])
      end

need to check on production !!!
will ping u again if got any issue!!!!
great discussion with u thanks!!!!

**Comment by ketanjm** [comment]
is it possible to end the session instead namspaces ?
i need multiple users login with diff sugarcrm account url!

**Comment by davidsulc** [comment]
(As an aside, rails sessions and caching should have nothing to do with this problem, so fell free to reactivate them. SugarCRM sessions are something completely different from rails sessions.)

I'll answer your second question first, regarding multiple users with different account urls:
as explained in the documentation, you can use multiple sessions simultaneously like this

```
ServerOne = SugarCRM.connect(URL1,...)
ServerOne::User.first
ServerTwo = SugarCRM.connect(URL2,...)
ServerTwo::User.first
```

`ServerOne` and `ServerTwo` can connect to different urls, use different user accounts, etc.

If you only need one active connection, and watch to switch users, you can do the following

```
ServerOne = SugarCRM.connect(URL1, usesr1, pass1)
puts ServerOne.current_user
ServerOne.reconnect(URL1, usesr2, pass2)
puts ServerOne.current_user
```

Next, your code fix: _I urge you not to consider this problem fixed_, as it is more than likely that this will eventually break in a very ugly fashion.

This is how namespaces work (since 0.9.11): each time you call `SugarCRM.connect`, a new namesapce is retruned, like `SugarCRM::NamespaceX` where X starts at 0 and is incremented each time you call `SugarCRM.connect`.

Here's the problem with your code: when you compare `@a ==  SugarCRM::Namespace1` you're simply checking if the returned namespace matches a very specific namespace. If, for some reason, you have 2 active namespaces (e.g. `SugarCRM::Namespace0` and `SugarCRM::Namespace2`), your code will fail to guarantee only one active session.

I'll try to reproduce this issue this week-end, but be aware your code (although apprently working for you) is not a solid fix. I'll keep you updated.

**Comment by davidsulc** [comment]
I'm unable to reproduce your problem using Rails 3 and gem version 0.9.11.

I've uploaded a trivial rails app here: https://github.com/davidsulc/sugar_on_rails_basic

See the commit history (https://github.com/davidsulc/sugar_on_rails_basic/commits/master) to see how the connection is initialized and used within the app.

Even quitting and restarting the server several times failed to cause the issue you've had (note the intializer contains no conditional logic relating to existing SugarCRM connections).

Can you try using this app and see if you still have issues? If you don't have any issues with this basic app, can you explain how you're using the gem/rails? You must be doing something special...

**Comment by davidsulc** [comment]
I've replaced this app: https://github.com/davidsulc/sugar_on_rails_basic

Take a look at it, the readme has all the specific steps necessary to use the sugarcrm gem within a Rails3 app.

Let me know if you run into any issues.
