### ISSUE TITLE
Use SugarCRM with Rails 2

### ISSUE THREAD

**Issue by alexdesi** [chicks/sugarcrm#54]
I used the SugarCRM gem with IRB, and it works well.
I know the documentation says:  
"The SugarCRM Ruby gem relies on ActiveSupport >= 3, and therefore isn’t compatible with Rails 2"
but I need to use it in a Rails 2.3.9 app.

I can't use: Run 'rails g sugarcrm:config' to generate the config, of course I can create manually the config file, but will it work ?
How I can do that ? there is some workaround to use SugarCRM in Rails 2 ?

Many Thanks
Alessandro

**Comment by davidsulc** [comment]
The SugarCRM gem relies on ActiveSupport >= 3, which won't work with Rails 2, as far as I know. Maybe chicks has an idea on how to get this working...

(Whether it work or not is unrelated to the config file: it could absolutely be created by hand.)

**Comment by chicks** [comment]
There are a number of ActiveSupport 3 core_extensions that aren't included in ActiveSupport 2.  The BIG one I can think of  is the "class_attribute" method.  I used to include these methods in my own core_extensions file to maintain rails 2 compatibility, but Rails 2 is REALLY dated.  I would highly recommend you move to Rails 3 if possible.  Otherwise, you can probably fork the gem and just copy/paste the active_support core_extensions that you need and update the require statements.

**Comment by jigfox** [comment]
@alexdesi see #55 we've backported the sugarcrm gem to rails 2.3 but you need at least rails 2.3.9, that's the version rails backported the `class_attribute` method from rails 3 to rails 2

**Comment by chicks** [comment]
Yeah, I'm going to take a look at the pull request tonight and if it all checks out I'll cut a new gem.

**Comment by davidsulc** [comment]
Oops. Merged before I saw your message :-p

Tested against Rails 3 (Ruby 1.8.7 and 1.9.2) and Rails 2.3.9 (Ruby 1.8.7).

@alexdesi if you use Bundler, you can point your Gemfile to git://github.com/chicks/sugarcrm.git for th sugarcrm gem, if not, you should be able to use it as soon as @chicks cuts a new gem.

(I'm a little slow today and closed this issue instead of the pull request... Nevertheless, I think @jigfox's work solves @alexdesi's issue.)

**Comment by chicks** [comment]
Yah, check out gem version 0.9.15.
