### ISSUE TITLE
Convert Leads to Contact

### ISSUE THREAD

**Issue by alexdesi** [chicks/sugarcrm#65]
Hi,
in the Sugar interface there is a way to convert Leads in Contact: Lead tab >> "Convert Lead"
Someone know the way to do that using this library ?

I had a look to 
SugarCRM::Lead.methods 
but I have not found nothing.

Some ideas ?

Thank you,
Alessandro

**Comment by alexdesi** [comment]
To be more specific I need to develop a typical use case:
1) find a lead by email
2) if exist convert it to contact
Issues I have found:
1)
l = SugarCRM::Lead.find_by_email1 'asdf'
SugarCRM::UnhandledResponse: Database failure. Please refer to sugarcrm.log for details.

I don't have access to the server, so I can't figure out what's happen

2) I have not found a way to convert lead to contact,
so maybe I can create a new contact and set:
lead.contact_id =  contact id,
lead.converted = true
I have to do some test, but this way doesn't convince me.

Do you have some better ideas ?

**Comment by davidsulc** [comment]
I'd check with @chicks, since he tends to have more experience with SugarCRM's inner workings.

I vaguely recall doing this once, and I would have suggested doing exactly what you mention:
1. create a new contact (but if you're using something like `Contact.new(lead.attributes)`, make sure you don't copy over the id value !)
2. set the `contact_id` value in the lead
3. set the lead's `converted` flag to true

According to my empirical observations, this is what happens through the GUI: the values are copied over (according to user selection and/or editing), `contact_id` is set, and `converted` flag is set. Note that once you convert a lead to a contact, the lead remains visible in CRM. If you don't want the lead to be visible, set the lead's `deleted` flag to true.

Hope this helps !

**Comment by alexdesi** [comment]
Thank David,
I've tried it, yes the process is more or less as you describe it,  I have to add that:
lead.converted = true doesn't change lead.status (I tried it), so you have also set lead.status = "Converted"  (status is a string)

But what about to get the lead that I want to convert ? 
I am trying using SugarCRM::Lead.find_by_email1 "email@email.com"
but I get this error:
SugarCRM::UnhandledResponse: Database failure. Please refer to sugarcrm.log for details.

(and I don't have access to the server, so I can't figure out what's happen)

Do you have any ideas ?
Thank you

**Comment by davidsulc** [comment]
Emails are kind of tricky, because they're not actual fields in the leads table. This should work : https://github.com/chicks/sugarcrm/issues/61

**Comment by chicks** [comment]
Closing this, unless it's still an issue!
